# Generated by Django 4.2.7 on 2023-11-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageBlog',
        ),
        migrations.RenameIndex(
            model_name='imageblog',
            new_name='blog_imageb_created_02b67d_idx',
            old_name='blog_image_created_1ba45b_idx',
        ),
    ]
