# Generated by Django 4.2.7 on 2023-11-07 17:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[500, 500], upload_to='account_images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[600, 400], upload_to='post_images/'),
        ),
    ]
