# Generated by Django 4.2.7 on 2023-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_imageblog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageblog',
            old_name='title',
            new_name='title_image',
        ),
        migrations.AlterField(
            model_name='imageblog',
            name='image_file',
            field=models.ImageField(height_field=200, upload_to='post_images/', width_field=200),
        ),
    ]
